### PR TITLE
Here

### PR DESCRIPTION
**Pull request by SPLATPLAYS**

### CODE REVIEW

**Comment by SPLATPLAYS** [comment]
I will rebase after you merge

**Comment by SPLATPLAYS** [comment]
also #24

**Comment by spacey-sooty** [comment]
> I will rebase after you merge

The whole point is you do it before you merge, you wouldn't have this issue if you just used branches properly

**Comment by SPLATPLAYS** [comment]
Made contact work properly, I misclicked and it'll be much easier when you merge

**Comment by spacey-sooty** [comment]
have you implemented the endpoint you link to in fetch?

**Comment by SPLATPLAYS** [comment]
yes

**Review by spacey-sooty — APPROVED** [review]
:ship: it I cant be bothered reviewing

**Comment by spacey-sooty** [comment]
Rebase and use branches properly in future please :slightly_smiling_face:

**Comment by SPLATPLAYS** [comment]
thx

**Pull request merged**
